// Generated by qa/build-runner-fall.mjs from registered alpha bounds.
export const INJURY_TOP_OFFSETS = Object.freeze([[79.23,71.81,51.89],[77.28,60.09,63.61],[82.75,83.14,82.75],[82.75,81.97,81.97],[89.16,71.81,62.44]].map(row => Object.freeze(row)));
