// Generated by qa/build-legacy-expressions.mjs from the normal atlas alpha bounds.
export const LEGACY_NPC_LAYOUT = Object.freeze({
  topOffsets: Object.freeze([74.72,69.15,56.98]),
  footOffsets: Object.freeze([41.19,41.19,40.78])
});
