import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.JELLY_PLAYWRIGHT_MODULE || 'playwright');
const port = process.env.JELLY_QA_PORT || '4189';
const server = spawn(process.execPath, ['server.mjs'], { env: { ...process.env, JELLY_PORT: port }, windowsHide: true });
let browser; const checks = [], errors = [];
await fs.mkdir('qa/gravity', { recursive: true });
try {
  await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); });
  browser = await chromium.launch({ headless: true, channel: process.env.JELLY_BROWSER_CHANNEL || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400 && r.url().startsWith(`http://localhost:${port}`)) errors.push(`${r.status()} ${r.url()}`); });
  await page.route('**/src/main.js*', async route => {
    const response = await route.fetch();
    await route.fulfill({ response, body: (await response.text()).replace('new Game();', 'window.__qaGame = new Game();') });
  });
  await page.goto(`http://localhost:${port}`, { waitUntil: 'networkidle' });
  await page.locator('#gravity-start').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'qa/gravity/home-desktop.png' });
  await page.locator('#gravity-start').click();
  await page.waitForFunction(() => window.__qaGame.state === 'playing');
  assert.equal(await page.evaluate(() => /gravity-map-v1/.test(window.__qaGame.worldRenderer.gravityImage?.src)), true);
  await page.evaluate(() => { window.__qaGame.debug.infiniteLife = true; });
  assert.equal(await page.locator('[data-item="PPA"]').isVisible(), false);
  assert.equal(await page.locator('[data-item="NAP"]').isVisible(), true);
  await page.keyboard.press('q'); assert.equal(await page.evaluate(() => window.__qaGame.itemSystem.selectedId), 'NAP');
  const before = await page.evaluate(() => window.__qaGame.player.x);
  await page.keyboard.down('ArrowLeft'); await page.waitForTimeout(200); await page.keyboard.up('ArrowLeft');
  assert.ok(await page.evaluate(() => window.__qaGame.player.x) < before);
  await page.keyboard.press('e'); assert.ok(await page.evaluate(() => window.__qaGame.bossCombat.cooldown) > 0);
  await page.screenshot({ path: 'qa/gravity/wave-desktop.png' });
  checks.push('Home entry and portrait, Sports map loaded, desktop keyboard movement/E, Q lock, only NAP visible');

  for (const [width, height] of [[390, 844], [375, 667]]) {
    await page.setViewportSize({ width, height });
    await page.evaluate(async () => { const g = window.__qaGame; await g.startStage('gravityOverload'); g.debug.infiniteLife = true; g.bossCombat.debug('wave3'); });
    const y = await page.evaluate(() => window.__qaGame.player.y);
    await page.locator('[data-dir="down"]').dispatchEvent('pointerdown', { pointerId: 8, pointerType: 'touch' });
    await page.waitForTimeout(180);
    await page.locator('[data-dir="down"]').dispatchEvent('pointerup', { pointerId: 8, pointerType: 'touch' });
    assert.ok(await page.evaluate(() => window.__qaGame.player.y) > y);
    await page.locator('#action-button').dispatchEvent('pointerdown', { pointerId: 9, pointerType: 'touch' });
    await page.locator('#action-button').dispatchEvent('pointerup', { pointerId: 9, pointerType: 'touch' });
    assert.ok(await page.evaluate(() => window.__qaGame.bossCombat.cooldown) > 0);
    const geometry = await page.evaluate(() => {
      const rect = s => { const r = document.querySelector(s).getBoundingClientRect(); return { x: r.x, y: r.y, right: r.right, bottom: r.bottom }; };
      return { nap: rect('[data-item="NAP"]'), use: rect('#action-button'), dpad: rect('.mobile-dpad') };
    });
    assert.ok(geometry.nap.x >= geometry.dpad.right && geometry.nap.bottom <= geometry.use.y, JSON.stringify(geometry));
    assert.ok(geometry.nap.bottom <= height && geometry.use.bottom <= height);
    await page.screenshot({ path: `qa/gravity/wave3-${width}.png` });
    await page.evaluate(() => window.__qaGame.bossCombat.startArrival());
    await page.waitForTimeout(700); await page.screenshot({ path: `qa/gravity/arrival-${width}.png` });
    await page.waitForFunction(() => window.__qaGame.bossCombat.state === 'BOSS');
    await page.evaluate(() => {
      const g = window.__qaGame, c = g.bossCombat;
      Object.assign(c.player, { x: 490, y: 700 }); Object.assign(c.boss, { x: 380, y: 570, phase: 3 });
      c.boss.attackIndex = 0; c.ground.clear(); c.boss.attack(c.player, c.ground);
      c.ground.add({ x: 570, y: 480, kind: 'crystal', owner: 'boss' });
      window.dispatchEvent(new Event('blur'));
    });
    const paused = await page.evaluate(() => JSON.stringify(window.__qaGame.bossCombat));
    await page.waitForTimeout(200); assert.equal(await page.evaluate(() => JSON.stringify(window.__qaGame.bossCombat)), paused);
    await page.locator('#background-resume').click();
    await page.screenshot({ path: `qa/gravity/fan-${width}.png` });
    await page.evaluate(() => { const g = window.__qaGame; g.bossCombat.boss.enter('FATIGUE', 2.5); g.bossCombat.ground.clear(); });
    await page.screenshot({ path: `qa/gravity/core-${width}.png` });
    assert.match(await page.locator('#boss-core-hint').innerText(), /NAP/);
    await page.evaluate(() => window.__qaGame.openExitConfirmation());
    const exitPaused = await page.evaluate(() => JSON.stringify(window.__qaGame.bossCombat));
    await page.waitForTimeout(150); assert.equal(await page.evaluate(() => JSON.stringify(window.__qaGame.bossCombat)), exitPaused);
    await page.locator('#exit-confirm-secondary').click();
    checks.push(`${width}×${height}: touch D-pad/Use, dock separation, arrival, visible fan/crystal/core, blur and exit freeze`);
  }
  await page.evaluate(() => {
    const c = window.__qaGame.bossCombat; c.director.clear(); c.boss.hp = 2;
    Object.assign(c.boss, { x: 380, y: 570 }); Object.assign(c.player, { x: 380, y: 660 });
    c.boss.enter('FATIGUE', 2.5); c.cooldown = 0; c.hitPause = 0; c.tryAction();
  });
  assert.equal(await page.evaluate(() => window.__qaGame.bossCombat.state), 'VICTORY');
  await page.waitForTimeout(2600); await page.screenshot({ path: 'qa/gravity/mini-flight.png' });
  await page.waitForFunction(() => window.__qaGame.bossCombat.state === 'COLLECT');
  assert.equal(await page.locator('#boss-result').isVisible(), false);
  assert.match(await page.locator('#boss-wave').innerText(), /收集重力核心/);
  assert.equal(await page.evaluate(() => window.__qaGame.coreCollectionStore.has('gravityCore')), false);
  assert.deepEqual(await page.evaluate(() => ({ x: window.__qaGame.bossCombat.coreDrop.x, y: window.__qaGame.bossCombat.coreDrop.y })), { x: 384, y: 576 });
  await page.screenshot({ path: 'qa/gravity/core-pickup-375.png' });
  await page.locator('[data-dir="up"]').dispatchEvent('pointerdown', { pointerId: 18, pointerType: 'touch' });
  await page.waitForFunction(() => window.__qaGame.state === 'result');
  await page.locator('[data-dir="up"]').dispatchEvent('pointerup', { pointerId: 18, pointerType: 'touch' });
  assert.equal(await page.locator('#boss-result').isVisible(), true);
  assert.match(await page.locator('#boss-result').innerText(), /重力痠痛危機/);
  assert.equal(await page.locator('#boss-result .core-reward').isVisible(), true);
  assert.match(await page.locator('#boss-result .core-reward').innerText(), /重力核心/);
  assert.equal(await page.evaluate(() => window.__qaGame.coreCollectionStore.has('gravityCore')), true);
  assert.equal(await page.evaluate(() => window.__qaGame.coreCollectionStore.has('itchCore')), false);
  await page.locator('#boss-core-reward button').click();
  assert.equal(await page.locator('#gravity-core-entry-name').innerText(), '重力核心');
  assert.equal(await page.locator('#gravity-core-entry-image').isVisible(), true);
  assert.equal(await page.locator('#core-entry-image').isVisible(), false);
  await page.screenshot({ path: 'qa/gravity/collection-375.png' });
  await page.locator('#core-collection-close').click();
  assert.equal(await page.locator('#boss-result-core-note').isVisible(), false);
  await page.locator('#boss-result-details summary').click();
  assert.match(await page.locator('#boss-item-hit-label').innerText(), /NAP/);
  for (const [width, height] of [[1280, 900], [390, 844], [375, 667], [320, 568], [667, 375]]) {
    await page.setViewportSize({ width, height });
    const r = await page.locator('#boss-home').boundingBox(); assert.ok(r.y >= 0 && r.y + r.height <= height);
    assert.ok(await page.locator('#boss-result').evaluate(el => el.scrollWidth <= innerWidth));
    await page.screenshot({ path: `qa/gravity/result-${width}.png` });
  }
  checks.push('Victory float-away, physical gravity core pickup, own collection reward, dedicated NAP result and fixed buttons in five viewports');
  await page.locator('#boss-replay').click(); await page.waitForFunction(() => window.__qaGame.state === 'playing');
  assert.equal(await page.evaluate(() => window.__qaGame.selectedStage), 'gravityOverload');
  await page.evaluate(() => {
    const c = window.__qaGame.bossCombat; window.__qaGame.debug.infiniteLife = false;
    for (let i = 0; i < 3; i++) { c.invulnerability = 0; c.damage(); }
  });
  await page.waitForFunction(() => window.__qaGame.state === 'gameover');
  assert.match(await page.locator('#boss-result-tip').innerText(), /NAP/);
  await page.setViewportSize({ width: 375, height: 667 });
  await page.screenshot({ path: 'qa/gravity/failure-375.png' });
  await page.locator('#boss-home').click();
  assert.equal(await page.locator('#home-screen').isVisible(), true);
  await page.evaluate(() => window.__qaGame.startStage('alienMosquito'));
  assert.equal(await page.locator('[data-item="PPA"]').isVisible(), true);
  assert.equal(await page.locator('[data-item="NAP"]').isVisible(), false);
  assert.match(await page.locator('#boss-core-hint').innerText(), /PPA/);
  await page.evaluate(() => window.__qaGame.startStage('sports'));
  assert.equal(await page.locator('[data-item="PPA"]').isVisible(), true);
  assert.equal(await page.locator('[data-item="NAP"]').isVisible(), true);
  await page.keyboard.press('q'); assert.equal(await page.evaluate(() => window.__qaGame.itemSystem.selectedId), 'NAP');
  assert.ok(await page.evaluate(() => window.__qaGame.npcs.length) > 0);
  checks.push('Replay remains gravity; actual heart loss gives failure, Home, mosquito PPA restoration, Sports rescue/Q/NPC restoration');
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.locator('#core-collection-count').innerText(), '1 / 2');
  await page.locator('.collection-home-button').click();
  assert.equal(await page.locator('#gravity-core-entry-name').innerText(), '重力核心');
  assert.equal(await page.locator('#core-entry-image').isVisible(), false);
  await page.locator('#core-collection-close').click();
  checks.push('Gravity core persists after reload and the encyclopedia keeps separate locked/unlocked entries');
  assert.deepEqual(errors, []);
  const report = { status: 'PASS', checks, errors, note: 'QA injects encounter states for visual coverage; full natural flow is tested separately by gravity-simulation.mjs.' };
  await fs.writeFile('qa/gravity/browser-report.json', JSON.stringify(report, null, 2) + '\n');
  console.log(JSON.stringify(report, null, 2));
} finally { await browser?.close(); server.kill(); }
